### ISSUE TITLE
How to get screenshot Object from "it"

### ISSUE THREAD

**Issue by abossjamlai** [bolteu/screenshotty#10]
I don't know Kotlin very well and in a part of code  in the Read Me , it says you can get screenshot object from "it".

val screenshotResult = screenshotManager.makeScreenshot()
val subscription = screenshotResult.observe(
   onSuccess = { processScreenshot(it) },
   onError = { onMakeScreenshotFailed(it) }
)

How can I get Screenshot object and get bitmap from that ?

**Comment by xzaleksey** [comment]
Hi,
It is described in section "Working with result". You just need to check result for type.

fun show(screenshot: Screenshot) {
   val bitmap = when (screenshot) {
      is ScreenshotBitmap -> screenshot.bitmap
   }
   screenshotPreview.setImageBitmap(bitmap)
}
