### ISSUE TITLE
PixelCopy BMP sizes are wrong

### ISSUE THREAD

**Issue by norbert-sziraczki** [bolteu/screenshotty#11]
The ScreenShotSpec taken from the window now uses the getSize method, that removes the soft buttons from the size, however the screenshot contains the part where it should be (in black) and the status bar as well. This makes the aspect ratio wrong. You should use getRealSize instead.

**Comment by xzaleksey** [comment]
Thank you. We will check and make a fix for this one.

**Comment by MirzaAhmedBaig** [comment]
is that done?

**Comment by yarolegovich** [comment]
Yes, the fix is in 1.0.3

**Comment by andy-weinstein** [comment]
I have an aspect-ratio issue on the Pixel 5 using version 1.0.3
It is stretched a bit vertically, seemingly including the top status area in the size that it writes the image into. I can't comment on the API's getSize or getRealSize - I don't have much experience there.
No issue on Samsung A7 or LG Nexus 5
